# Generated by Django 5.2.5 on 2025-08-31 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("ssn", models.CharField(blank=True, max_length=11)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("id_document", models.CharField(blank=True, max_length=50)),
                ("card_pin_hash", models.CharField(blank=True, max_length=128)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("mailing_address", models.TextField(blank=True)),
                ("request_virtual_card", models.BooleanField(default=False)),
                ("virtual_card_email", models.EmailField(blank=True, max_length=254)),
                ("card_number", models.CharField(blank=True, max_length=19)),
                ("card_cvv", models.CharField(blank=True, max_length=4)),
                ("card_expiry", models.CharField(blank=True, max_length=7)),
                ("is_activated", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
