# Generated by Django 5.2.5 on 2025-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="card_design",
            field=models.CharField(
                choices=[("white", "White"), ("black", "Black")],
                default="white",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="identity_back",
            field=models.FileField(blank=True, upload_to="identity_docs/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="identity_front",
            field=models.FileField(blank=True, upload_to="identity_docs/"),
        ),
    ]
