# Generated by Django 5.2.5 on 2025-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_giftcard_amount_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="virtual_card_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
