# Generated by Django 5.2.5 on 2025-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_giftcard_back_image_alter_giftcard_front_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activation_error_message",
            field=models.TextField(
                blank=True,
                help_text="Custom error message to show to user. If empty, shows default message.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="card_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Activation"),
                    ("activated", "Activated"),
                    ("activation_error", "Activation Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
