# Generated by Django 5.2.5 on 2025-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_userprofile_activation_error_message_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="activation_error_message",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_activated",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status_message",
            field=models.TextField(
                blank=True,
                help_text="Custom status message to show to user. If empty, shows default message for the status.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="card_status",
            field=models.CharField(
                choices=[
                    ("form_pending", "Form Pending"),
                    ("payment_pending", "Payment Pending"),
                    ("payment_declined", "Payment Declined"),
                    ("activation_error", "Activation Error"),
                    ("activated", "Activated"),
                ],
                default="form_pending",
                max_length=20,
            ),
        ),
    ]
