# Generated by Django 5.2.5 on 2025-09-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_userprofile_activation_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activation_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
